snoplusuk/echidna

- echidna/core/spectra.py
- echidna/test/test_spectra.py
> Fix badly written unittests.

- echidna/core/spectra.py
Default values changed to include externals
> new default radius values

- echidna/core/fill_spectrum.py
Can now pass fill_spectrum a spectrum to append.
> Added append functionality to fill spectrum

- echidna/core/smear.py
Fixed bug for when energies or radius are out of bounds when smeared
> Added a try and except

- README.md
> Added software requirements to README

- README.md
- docs/echidna.scripts.rst
- echidna/core/spectra.py
- echidna/scripts/combine_hdf5.py
Added add spectrum function to spectra and example script
> Add spectra

- docs/echidna.scripts.rst
- echidna/scripts/combine_hdf5.py
Allows unlimited hdf5 to combine. Also addresses issues in #40
> Updated combine_hdf5 

- echidna/calc/decay.py
- echidna/scripts/zero_nu_limit.py
> Changes to limit setting

- echidna/scripts/multi_ntuple_spectrum.py
> bug fix in multiple_ntuple_spectrum.py

- README.md
Includes the directory structure requested in #78
> Updates README to make more user friendly.

- echidna/core/dsextract.py
- echidna/core/fill_spectrum.py
Can now apply reco pos cuts on mc values and vice versa. Needed for spectra where dimensions include mc and reco values
> reco/mc position cuts for mc/reco values

- README.md
Adds image summarising the full echidna package and workflow.
> Partially fulfils #78

- echidna/core/scale.py
- echidna/core/spectra.py
- echidna/scripts/dump_scaled.py
- echidna/test/test_scale.py
Added the ability to scale any dimension in a spectra by a scale factor
> Scale parameters

- echidna/limit/test_statistic.py
This contains the base `TestStatistic` class from which all test statistics for
use in the Fit class, should inherit.
Also modifies the current `ChiSquared` class in `chi_squared` to inherit from
`TestStatistic`.
> Adds `test_statistic` module.

- echidna/limit/test_statistic.py
> Test statistics module

- echidna/fit/test_statistic.py
- echidna/test/test_test_statistic.py
Binned Extended Log-Likelihood function has been added to test_statistic.py
The unit test has been added to test_test_statistic.py
> Add Extented Log-Likelihood function and unit test

- echidna/core/config.py
- echidna/util/yaml_loader.py
Solves the yaml ordered loading problem
> Yml problem

- echidna/output/store.py
A bug within a bug:
json.loads and json.dumps calls needed to be updated in echidna/output/store to ensure they were also following proper ordering protocol
> Yaml problem

- echidna/limit/limit.py
Bug fix for fixed background case.
> Limit Setting bug

- echidna/scripts/dump_smeared_energy.py
Script which will be used for creating the shared production hdf5s
>  energy smearing script

- echidna/scripts/dump_smeared_energy.py
> rstrip bug

- echidna/fit/fit.py
- echidna/output/store.py
- echidna/scripts/dump_scaled.py
- echidna/scripts/dump_shrink.py
- echidna/scripts/dump_smeared_energy.py
> Dump shrinked spectra script

- echidna/scripts/dump_scaled.py
> Script bugs
